household/home画面を作成した。
yoroduyaken/household-app pull request #7
Opened 2022-04-15 04:34 UTC by yoroduyaken

2022-04-15 05:16 UTC, Sunasuna24 requested changes
`layout.blade.php`について1点お伺いしたいことがあります！
こちらのviewファイルを「layout」と命名していますが、こちらは将来的にレイアウトとして使用する想定なのでしょうか！？？

2022-04-15 05:16 UTC, Sunasuna24 commented on routes/web.php
> +});
このrouteは恐らくかなりの頻度で使用すると思われるので、このrouteには名前を付けてあげましょう！

将来的にほかの人と一緒に開発するときにコードは実装したご自身以外の開発者にも分かりやすくないといけないので、今回付ける名前は例えば`home`や`dashboard`などにするとかなり良いと思います！👍

2022-04-15 05:20 UTC, Sunasuna24 commented on routes/web.php
> +});
追記です！
同ファイルのログインのrouteもめちゃ使う気がするので、ログインにも名前を付けちゃいましょう☺

2022-04-15 05:20 UTC, yoroduyaken commented on routes/web.php
> +});
的確なご指摘ありがとうございます。
layoutは、home画面の意味でつけただけですのでhomeに修正させて頂きます。

2022-04-15 05:24 UTC, yoroduyaken commented on routes/web.php
> +});
度々、すみません。
homeにすると、「/」のトップページに画面が遷移されるので、
dashboardにします。

2022-04-15 06:22 UTC, Sunasuna24 requested changes
2点修正があります！ご対応お願いいたします✨

2022-04-15 06:22 UTC, Sunasuna24 commented on resources/views/layout.blade.php
> +</html>
同じ中身のファイルが別であるので、こちらのviewファイルは削除していただいて大丈夫です🙆

2022-04-15 06:22 UTC, Sunasuna24 commented on routes/web.php
> +});
name関数を使ってrouteに名前を付けましょう！
詳細はslackでご連絡差し上げます🙇

2022-04-16 07:47 UTC, Sunasuna24 requested changes
いいですね、途中まで🙆‍♂️です！

以下の3点をクリアしましょう！
1. `layout.blade.php`と`dashboard.blade.php`の中身が一緒なので、`layout.blade.php`は消しちゃいましょう👍
2. `/`と`/home`にアクセスしたときで表示される画面が同じなので、`/`にアクセスしたときのトップページを作りましょう！（前に一度作りましたが😂）
3. `/`にアクセスしたときのrouteにも名前を着けましょう👍

2022-04-16 08:38 UTC, Sunasuna24 approved these changes
LGTM👍

2022-04-16 08:40 UTC, merged